/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of TransactionInput.xs. Do not edit this file, edit TransactionInput.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "TransactionInput.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include <stdio.h>
#include <ctype.h>
#include <openssl/ssl.h>
#include <openssl/ripemd.h>
#include <openssl/rand.h>
#include <CBHDKeys.h>
#include <CBChecksumBytes.h>
#include <CBAddress.h>
#include <CBWIF.h>
#include <CBByteArray.h>
#include <CBBase58.h>
#include <CBScript.h>
#include <CBTransactionInput.h>


// print CBByteArray to hex string
char* bytearray_to_hexstring(CBByteArray * serializeddata,uint32_t dlen){
	char* answer = malloc(dlen*sizeof(char*));
	CBByteArrayToString(serializeddata, 0, dlen, answer, 0);
	return answer;
}
CBByteArray* hexstring_to_bytearray(char* hexstring){
	CBByteArray* answer = CBNewByteArrayFromHex(hexstring);
	return answer;
}

//bool CBInitScriptFromString(CBScript * self, char * string)
char* scriptToString(CBScript* script){
	char* answer = (char *)malloc(CBScriptStringMaxSize(script)*sizeof(char));
	CBScriptToString(script, answer);
	return answer;

}
// CBScript * script = CBNewScriptFromString(scriptstring);

CBTransactionInput* stringToTransactionInput(char* scriptstring, int sequenceInt, char* prevOutHashString, int prevOutIndexInt){
	// prevOutHash is stored as a hex
	CBByteArray* prevOutHashInReverse =  CBNewByteArrayFromHex(prevOutHashString);
	CBScript* script = CBNewScriptFromString(scriptstring);


	// need to reverse the prevOutHashString...
	CBByteArray* prevOutHash = CBByteArrayCopy(prevOutHashInReverse);
        CBByteArrayReverseBytes(prevOutHash);
	CBFreeByteArray(prevOutHashInReverse);

	CBTransactionInput* txinput = CBNewTransactionInput(
				script,
				(uint32_t)sequenceInt,
				prevOutHash,
				(uint32_t)prevOutIndexInt
			);

	//CBFreeScript(script);
	//CBDestroyByteArray(prevOutHash);
	return txinput;
}

CBTransactionInput* serializeddata_to_obj(char* datastring){

	CBByteArray* data = hexstring_to_bytearray(datastring);

	CBTransactionInput* txinput = CBNewTransactionInputFromData(data);
	int dlen = (int)CBTransactionInputDeserialise(txinput);

	//CBTransactionInputDeserialise(txinput);
	//CBDestroyByteArray(data);
	return txinput;
}

char* obj_to_serializeddata(CBTransactionInput * txinput){
	CBTransactionInputPrepareBytes(txinput);
	int dlen = CBTransactionInputSerialise(txinput);
	CBByteArray* serializeddata = CBGetMessage(txinput)->bytes;

	char* answer = bytearray_to_hexstring(serializeddata,dlen);

	return answer;
}



//////////////////////// perl export functions /////////////
//CBTransactionInput * CBNewTransactionInput(CBScript * script, uint32_t sequence, CBByteArray * prevOutHash, uint32_t prevOutIndex)
char* create_txinput_obj(char* scriptstring, int sequenceInt, char* prevOutHashString, int prevOutIndexInt){
	CBTransactionInput* txinput = stringToTransactionInput(scriptstring,sequenceInt,prevOutHashString,prevOutIndexInt);
	char* answer = obj_to_serializeddata(txinput);
	//CBFreeTransactionInput(txinput);
	return answer;
}

char* get_script_from_obj(char* serializedDataString){
	CBTransactionInput* txinput = serializeddata_to_obj(serializedDataString);
	char* scriptstring = scriptToString(txinput->scriptObject);
	//CBFreeTransactionInput(txinput);
	return scriptstring;
}
char* get_prevOutHash_from_obj(char* serializedDataString){
	CBTransactionInput* txinput = serializeddata_to_obj(serializedDataString);
	CBByteArray* dataInReverse = txinput->prevOut.hash;
	CBByteArray* data = CBByteArrayCopy(dataInReverse);
	CBByteArrayReverseBytes(data);
	char * answer = bytearray_to_hexstring(data,data->length);
	return answer;
}
int get_prevOutIndex_from_obj(char* serializedDataString){
	CBTransactionInput* txinput = serializeddata_to_obj(serializedDataString);
	uint32_t index = txinput->prevOut.index;
	CBFreeTransactionInput(txinput);
	return (int)index;
}
int get_sequence_from_obj(char* serializedDataString){
	CBTransactionInput* txinput = serializeddata_to_obj(serializedDataString);
	uint32_t sequence = txinput->sequence;
	CBFreeTransactionInput(txinput);
	return (int)sequence;
}




#line 136 "TransactionInput.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 188 "TransactionInput.c"

XS(XS_CBitcoin__TransactionInput_create_txinput_obj); /* prototype to pass -Wmissing-prototypes */
XS(XS_CBitcoin__TransactionInput_create_txinput_obj)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "scriptstring, sequenceInt, prevOutHashString, prevOutIndexInt");
    {
	char *	scriptstring = (char *)SvPV_nolen(ST(0));
	int	sequenceInt = (int)SvIV(ST(1));
	char *	prevOutHashString = (char *)SvPV_nolen(ST(2));
	int	prevOutIndexInt = (int)SvIV(ST(3));
	char *	RETVAL;
	dXSTARG;

	RETVAL = create_txinput_obj(scriptstring, sequenceInt, prevOutHashString, prevOutIndexInt);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_CBitcoin__TransactionInput_get_script_from_obj); /* prototype to pass -Wmissing-prototypes */
XS(XS_CBitcoin__TransactionInput_get_script_from_obj)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "serializedDataString");
    {
	char *	serializedDataString = (char *)SvPV_nolen(ST(0));
	char *	RETVAL;
	dXSTARG;

	RETVAL = get_script_from_obj(serializedDataString);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_CBitcoin__TransactionInput_get_prevOutHash_from_obj); /* prototype to pass -Wmissing-prototypes */
XS(XS_CBitcoin__TransactionInput_get_prevOutHash_from_obj)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "serializedDataString");
    {
	char *	serializedDataString = (char *)SvPV_nolen(ST(0));
	char *	RETVAL;
	dXSTARG;

	RETVAL = get_prevOutHash_from_obj(serializedDataString);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_CBitcoin__TransactionInput_get_prevOutIndex_from_obj); /* prototype to pass -Wmissing-prototypes */
XS(XS_CBitcoin__TransactionInput_get_prevOutIndex_from_obj)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "serializedDataString");
    {
	char *	serializedDataString = (char *)SvPV_nolen(ST(0));
	int	RETVAL;
	dXSTARG;

	RETVAL = get_prevOutIndex_from_obj(serializedDataString);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_CBitcoin__TransactionInput_get_sequence_from_obj); /* prototype to pass -Wmissing-prototypes */
XS(XS_CBitcoin__TransactionInput_get_sequence_from_obj)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "serializedDataString");
    {
	char *	serializedDataString = (char *)SvPV_nolen(ST(0));
	int	RETVAL;
	dXSTARG;

	RETVAL = get_sequence_from_obj(serializedDataString);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_CBitcoin__TransactionInput); /* prototype to pass -Wmissing-prototypes */
XS(boot_CBitcoin__TransactionInput)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        newXS("CBitcoin::TransactionInput::create_txinput_obj", XS_CBitcoin__TransactionInput_create_txinput_obj, file);
        newXS("CBitcoin::TransactionInput::get_script_from_obj", XS_CBitcoin__TransactionInput_get_script_from_obj, file);
        newXS("CBitcoin::TransactionInput::get_prevOutHash_from_obj", XS_CBitcoin__TransactionInput_get_prevOutHash_from_obj, file);
        newXS("CBitcoin::TransactionInput::get_prevOutIndex_from_obj", XS_CBitcoin__TransactionInput_get_prevOutIndex_from_obj, file);
        newXS("CBitcoin::TransactionInput::get_sequence_from_obj", XS_CBitcoin__TransactionInput_get_sequence_from_obj, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

