var annotated =
[
    [ "CBAddress", "struct_c_b_address.html", "struct_c_b_address" ],
    [ "CBAddressVT", "struct_c_b_address_v_t.html", "struct_c_b_address_v_t" ],
    [ "CBBigInt", "struct_c_b_big_int.html", "struct_c_b_big_int" ],
    [ "CBBlock", "struct_c_b_block.html", "struct_c_b_block" ],
    [ "CBBlockVT", "struct_c_b_block_v_t.html", "struct_c_b_block_v_t" ],
    [ "CBByteArray", "struct_c_b_byte_array.html", "struct_c_b_byte_array" ],
    [ "CBByteArrayVT", "struct_c_b_byte_array_v_t.html", "struct_c_b_byte_array_v_t" ],
    [ "CBDependencies", "struct_c_b_dependencies.html", "struct_c_b_dependencies" ],
    [ "CBEngine", "struct_c_b_engine.html", "struct_c_b_engine" ],
    [ "CBEngineVT", "struct_c_b_engine_v_t.html", "struct_c_b_engine_v_t" ],
    [ "CBEvents", "struct_c_b_events.html", "struct_c_b_events" ],
    [ "CBMessage", "struct_c_b_message.html", "struct_c_b_message" ],
    [ "CBMessageVT", "struct_c_b_message_v_t.html", "struct_c_b_message_v_t" ],
    [ "CBNetworkParameters", "struct_c_b_network_parameters.html", "struct_c_b_network_parameters" ],
    [ "CBNetworkParametersVT", "struct_c_b_network_parameters_v_t.html", "struct_c_b_network_parameters_v_t" ],
    [ "CBObject", "struct_c_b_object.html", "struct_c_b_object" ],
    [ "CBObjectVT", "struct_c_b_object_v_t.html", "struct_c_b_object_v_t" ],
    [ "CBScript", "struct_c_b_script.html", "struct_c_b_script" ],
    [ "CBScriptVT", "struct_c_b_script_v_t.html", "struct_c_b_script_v_t" ],
    [ "CBSha256Hash", "struct_c_b_sha256_hash.html", "struct_c_b_sha256_hash" ],
    [ "CBSha256HashVT", "struct_c_b_sha256_hash_v_t.html", "struct_c_b_sha256_hash_v_t" ],
    [ "CBSharedData", "struct_c_b_shared_data.html", "struct_c_b_shared_data" ],
    [ "CBTestStruct", "struct_c_b_test_struct.html", "struct_c_b_test_struct" ],
    [ "CBTestStructVT", "struct_c_b_test_struct_v_t.html", "struct_c_b_test_struct_v_t" ],
    [ "CBTransaction", "struct_c_b_transaction.html", "struct_c_b_transaction" ],
    [ "CBTransactionInput", "struct_c_b_transaction_input.html", "struct_c_b_transaction_input" ],
    [ "CBTransactionInputVT", "struct_c_b_transaction_input_v_t.html", "struct_c_b_transaction_input_v_t" ],
    [ "CBTransactionOutput", "struct_c_b_transaction_output.html", "struct_c_b_transaction_output" ],
    [ "CBTransactionOutputVT", "struct_c_b_transaction_output_v_t.html", "struct_c_b_transaction_output_v_t" ],
    [ "CBTransactionVT", "struct_c_b_transaction_v_t.html", "struct_c_b_transaction_v_t" ],
    [ "CBVarInt", "struct_c_b_var_int.html", "struct_c_b_var_int" ],
    [ "CBVersionChecksumBytes", "struct_c_b_version_checksum_bytes.html", "struct_c_b_version_checksum_bytes" ],
    [ "CBVersionChecksumBytesVT", "struct_c_b_version_checksum_bytes_v_t.html", "struct_c_b_version_checksum_bytes_v_t" ]
];