Document: cbitcoin
Title: Debian cbitcoin Manual
Author: <insert document author here>
Abstract: This manual describes what cbitcoin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cbitcoin/cbitcoin.sgml.gz

Format: postscript
Files: /usr/share/doc/cbitcoin/cbitcoin.ps.gz

Format: text
Files: /usr/share/doc/cbitcoin/cbitcoin.text.gz

Format: HTML
Index: /usr/share/doc/cbitcoin/html/index.html
Files: /usr/share/doc/cbitcoin/html/*.html
