Document: cbitcoin
Title: Debian cbitcoin Manual
Author: Joel DeJesus (Work Email) <dejesus.joel@e-flamingo.jp>
Abstract: Use cbitcoin as a bitcoin full node

Section: extra

Format: debiandoc-sgml
Files: /usr/share/doc/cbitcoin/cbitcoin.sgml.gz

Format: postscript
Files: /usr/share/doc/cbitcoin/cbitcoin.ps.gz

Format: text
Files: /usr/share/doc/cbitcoin/cbitcoin.text.gz

Format: HTML
Index: /usr/share/doc/cbitcoin/html/index.html
Files: /usr/share/doc/cbitcoin/html/*.html
