## This file generated by InlineX::C2XS (version 0.22) using Inline::C (version 0.5)
package CBitcoin::Script;

require Exporter;
*import = \&Exporter::import;
require DynaLoader;

$CBitcoin::Script::VERSION = '0.01';

DynaLoader::bootstrap CBitcoin::Script $CBitcoin::Script::VERSION;

@CBitcoin::Script::EXPORT = ();
@CBitcoin::Script::EXPORT_OK = ();

sub dl_load_flags {0} # Prevent DynaLoader from complaining and croaking

sub address_to_script {
	my $address = shift;
	return addressToScript($address);
}

sub pubkey_to_script {
	my $pubkey = shift;
	return pubkeyToScript($pubkey);
}

sub multisig_to_script {
	my $publickey = shift;
	my ($m,$n) = (shift,shift);
	# make sure that m,n are valid numbers
	unless($n =~ m/\d+/ && $n =~ m/\d+/){
		die "m,n are not properly set.\n";
	}
	if($m >= 2**8 || $n >= 2**8 || $m <= 0 || $n <= 0 || $m > $n){
		die "m,n are not properly set.\n";
	}
	return CBitcoin::Script::multisigToScript(\@arraypubkeys,$m,$n);
	
}

1;
