--- #YAML:1.0
name:               Crypt-PBC
version:            0.9000
abstract:           OO interface for the Stanford PBC library
author:
    - Paul Miller <jettero@cpan.org>
license:            LGPL
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Math::BigInt:       0
    Math::BigInt::GMP:  0
    MIME::Base64:       0
    perl:               5.006001
resources:
    repository:  http://github.com/jettero/crypt--pbc/
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:
    - pbc
    - ecc
    - crypt
    - boneh
    - ibe
