/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of CBitcoin.xs. Do not edit this file, edit CBitcoin.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "CBitcoin.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include <stdio.h>
#include <ctype.h>
#include <openssl/ssl.h>
#include <openssl/ripemd.h>
#include <openssl/rand.h>
#include <CBHDKeys.h>
#include <CBChecksumBytes.h>
#include <CBAddress.h>
#include <CBWIF.h>
#include <CBByteArray.h>
#include <CBBase58.h>


#include "ppport.h"


#line 30 "CBitcoin.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 82 "CBitcoin.c"

XS(XS_CBitcoin_hello); /* prototype to pass -Wmissing-prototypes */
XS(XS_CBitcoin_hello)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 25 "CBitcoin.xs"
    printf("Hello, world!\n");
#line 97 "CBitcoin.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_CBitcoin_is_even); /* prototype to pass -Wmissing-prototypes */
XS(XS_CBitcoin_is_even)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "input");
    {
	int	input = (int)SvIV(ST(0));
	int	RETVAL;
	dXSTARG;
#line 31 "CBitcoin.xs"
    RETVAL = (input % 2 == 0);
#line 119 "CBitcoin.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_CBitcoin_newMasterKey); /* prototype to pass -Wmissing-prototypes */
XS(XS_CBitcoin_newMasterKey)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "arg");
    {
	int	arg = (int)SvIV(ST(0));
	int	RETVAL;
	dXSTARG;
#line 39 "CBitcoin.xs"
    CBHDKey * masterkey = CBNewHDKey(true);
    CBHDKeyGenerateMaster(masterkey,true);

    uint8_t * keyData = malloc(CB_HD_KEY_STR_SIZE);
    CBHDKeySerialise(masterkey, keyData);
    free(masterkey);
    CBChecksumBytes * checksumBytes = CBNewChecksumBytesFromBytes(keyData, 82, false);
    // need to figure out how to free keyData memory
    CBByteArray * str = CBChecksumBytesGetString(checksumBytes);
    CBReleaseObject(checksumBytes);
    RETVAL = 1;
#line 152 "CBitcoin.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_CBitcoin); /* prototype to pass -Wmissing-prototypes */
XS(boot_CBitcoin)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        newXS("CBitcoin::hello", XS_CBitcoin_hello, file);
        newXS("CBitcoin::is_even", XS_CBitcoin_is_even, file);
        newXS("CBitcoin::newMasterKey", XS_CBitcoin_newMasterKey, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

